### ISSUE TITLE
Design the interface for DB connection during learning stage

### ISSUE THREAD

**Issue by kihyuk-nam** [traindb-project/traindb-ml#2]
[AS-IS]
(DBMS) --> CSV --> Learn

[TO-BE]
DBMS or CSV --> Learn

- option 1: extend the DataLoader (in PyTorch) to accept args for DBconn (uri, user/pass, ...)

Related to: https://github.com/traindb-project/traindb/issues/11#issue-1241519433

See: [Architecture](https://github.com/traindb-project/traindb-ml/wiki/Architecture), [Execution Flows](https://github.com/traindb-project/traindb-ml/wiki/Flows)

**Comment by kihyuk-nam** [comment]
Firstly, Dataset(not DataLoader) needs to be extended to accept info on dbconn

class DBDataset(Dataset):
  def __init__(self, uri='mysql://nam@traindb.org:3306', db_name='instacart', credential, batch_size):
    ...

**Comment by taewhi** [comment]
You can check JayDeBeApi for load data from DBMS.
https://pypi.org/project/JayDeBeApi/

**Comment by kihyuk-nam** [comment]
cf.
- https://discuss.pytorch.org/t/dataloader-and-postgres-or-other-sql-an-option/25927
- https://github.com/pytorch/pytorch/issues/20822
