### ISSUE TITLE
Branching rule

### ISSUE THREAD

**Issue by kihyuk-nam** [traindb-project/traindb-ml#20]
I hope the main branch be clean.
By clean I mean all the codes achieved consensus among participants.
How about the following branching rule?
1. write codes on personal branches
2. PR the codes that need to be merged
3. everyone reviews the 'PR'ed codes (add comments)
4. merge them only after reaching an agreement

@sungsoo @1jolee

**Comment by sungsoo** [comment]
I agree with your opinion.
So I forked the repository for personal workspace.
I'll send the merge request for the main traindb-ml repository if the merge is needed.

Thank you.
